name: changelog-bot
on:
  pull_request:
    types:
      - opened
jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: jungwinter/comment@v1
        with:
          type: create
          body: "**HOWDY! This is your friendly** :robot: **CHANGELOG bot** :robot:

            ------------------------------------------------------------------------


            Please don't forget to add a clear and succinct description of your change
            under the **Develop** header in `docs_rtd/changelog.rst`, if applicable. This will
            help us with the release process. See the [Contribution checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html#how-to-submit-a-pull-request)
            in the Great Expectations documentation for the type of labels to use!


            :sparkles: **Thank you!** :sparkles:"
          issue_number: ${{github.event.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
